name: healinq
description: HealinQ - Mental Health Companion App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_bottom.png
    - assets/images/logo_healinq.png
    - assets/images/maskot1.png
    - assets/images/maskot2.png
    - assets/images/jar.png
    - assets/images/envelope.png
    - assets/icons/ic_fyp.png
    - assets/icons/ic_konsultasi.png
    - assets/icons/ic_self_healing.png
    - assets/icons/home_grey.png
    - assets/icons/konsul_grey.png
    - assets/icons/selfheal_grey.png
    - assets/icons/fyp_grey.png

